import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { JSDOM } from 'jsdom';
import { renderOperationsPage } from '../src/operations/template.mjs';
const script=await fs.readFile(new URL('../assets/operations.js',import.meta.url),'utf8');
const config={enabled:true,deploymentMode:'staging',persistence:'firestore',aiMode:'local-guidance',paperless:true};
const response=(body,status=200,type='application/json')=>({ok:status>=200&&status<300,status,headers:{get:()=>type},json:async()=>body,text:async()=>typeof body==='string'?body:JSON.stringify(body)});
const flush=async()=>{for(let i=0;i<8;i++)await new Promise(r=>setTimeout(r,0));};
async function setup(handler,url='https://staging.example.test/operations.html'){
 const dom=new JSDOM(renderOperationsPage('ar'),{url,runScripts:'outside-only'});dom.window.fetch=handler;dom.window.confirm=()=>true;
 Object.defineProperty(dom.window,'crypto',{value:{randomUUID:()=> '11111111-1111-4111-8111-111111111111'},configurable:true});
 dom.window.HTMLDialogElement.prototype.showModal=function(){this.open=true;};dom.window.HTMLDialogElement.prototype.close=function(){this.open=false;};dom.window.eval(script);await flush();return dom;
}
function apiWith({permissions=[],requests=[],status=200,me={principal:{subject:'sub-1',email:'viewer@example.test',role:'viewer',orgId:'org-1'},permissions,roles:['viewer']}}={}){
 return path=>{if(path==='/api/ops/config')return Promise.resolve(response(config,status));if(path==='/api/ops/me')return Promise.resolve(response(me));if(path.startsWith('/api/ops/requests?'))return Promise.resolve(response({items:requests,nextCursor:null}));if(/^\/api\/ops\/(clients|tasks|documents)\?/.test(path))return Promise.resolve(response({items:[],nextCursor:null}));throw Error(`Unexpected request: ${path}`);};
}
test('واجهة Staging الفارغة تعرض حالة صريحة ولا تختلق أرقاماً أو سجلات',async()=>{
 const dom=await setup(apiWith()),d=dom.window.document;assert.match(d.querySelector('#ops-content').textContent,/لا توجد سجلات بعد/);assert.match(d.querySelector('#ops-content').textContent,/بيئة Staging فارغة/);assert.equal(d.querySelectorAll('.ops-record').length,0);assert.equal(d.querySelectorAll('#ops-toolbar-action button').length,0);dom.window.close();
});
test('فشل config بخدمة معطلة لا يعرض نجاحاً أو واجهة حفظ',async()=>{
 const dom=await setup(path=>{assert.equal(path,'/api/ops/config');return Promise.resolve(response({error:'disabled'},503));}),d=dom.window.document;assert.match(d.querySelector('#ops-content').textContent,/تم إيقاف النظام خادمياً/);assert.equal(d.querySelector('#ops-content').textContent.includes('تم الحفظ عبر الخادم'),false);assert.equal(d.querySelectorAll('#ops-toolbar-action button').length,0);dom.window.close();
});
test('الدور لا يأتي من العميل: لا role switch ولا أزرار كتابة لمستخدم viewer بلا صلاحيات',async()=>{
 const calls=[];const dom=await setup((path,options={})=>{calls.push([path,options]);return apiWith()(path,options);}),d=dom.window.document;assert.equal(d.querySelector('[name="role"]'),null);assert.equal(d.querySelector('#role-select'),null);assert.equal(d.querySelectorAll('#ops-toolbar-action button').length,0);assert.ok(calls.every(([,o])=>!String(o.body||'').includes('role')));dom.window.close();
});
test('قيم API غير الموثوقة تضاف كنص ولا تتحول إلى HTML قابل للتنفيذ',async()=>{
 const payload='<img src=x onerror="window.__xss=1">طلب غير موثوق';const dom=await setup(apiWith({requests:[{id:'req-1',version:1,title:payload,companyName:'شركة',contactName:'اسم',email:'x@example.test',phone:'1',service:'خدمة',city:'مدينة',description:payload,priority:'normal',status:'new'}]})),d=dom.window.document;d.querySelector('[data-section="requests"]').click();await flush();assert.match(d.querySelector('#ops-content').textContent,/طلب غير موثوق/);assert.equal(d.querySelectorAll('#ops-content img').length,0);assert.equal(dom.window.__xss,undefined);dom.window.close();
});
test('كتابة طلب تستخدم headers المطلوبة ومفتاح idempotency ولا ترسل حقول خادمية أو دور عميل',async()=>{
 const writes=[];const dom=await setup(async(path,options={})=>{if(path==='/api/ops/config')return response(config);if(path==='/api/ops/me')return response({principal:{subject:'sub-2',email:'operator@example.test',role:'operator',orgId:'org-1'},permissions:['requests:write'],roles:['operator']});if(/^\/api\/ops\/(requests|clients|tasks|documents)\?/.test(path))return response({items:[],nextCursor:null});if(path==='/api/ops/requests'&&options.method==='POST'){writes.push(options);return response({item:{id:'server-id',version:1,status:'new',createdAt:'2026-10-08T00:00:00Z',title:'طلب جديد'}});}throw Error(path);});
 const d=dom.window.document;d.querySelector('[data-section="requests"]').click();await flush();d.querySelector('#ops-toolbar-action button').click();const form=d.querySelector('#ops-form');const values={title:'طلب جديد',companyName:'شركة',contactName:'مسؤول',email:'contact@example.test',phone:'0500000000',service:'خدمة',city:'الرياض',description:'وصف صالح'};for(const[n,v]of Object.entries(values))form.elements.namedItem(n).value=v;assert.equal(form.checkValidity(),true);form.dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));await flush();assert.equal(writes.length,1);const o=writes[0];assert.equal(o.headers['Content-Type'],'application/json');assert.equal(o.headers['X-Fursan-Intent'],'operations');assert.equal(o.headers['Idempotency-Key'],'11111111-1111-4111-8111-111111111111');const body=JSON.parse(o.body);assert.deepEqual(Object.keys(body).sort(),['city','companyName','contactName','description','email','phone','priority','service','title']);assert.equal('id'in body||'version'in body||'status'in body||'createdAt'in body||'role'in body,false);dom.window.close();
});
test('اعتماد مصدر AI يحدث إصدار الطلب المحلي ويمكّن المسودة بدل البقاء عند نسخة قديمة',async()=>{
 let record={id:'request-1',version:1,status:'new',title:'مصدر اختبار'};const writes=[];
 const dom=await setup(async(path,options={})=>{if(path==='/api/ops/config')return response({...config,aiMode:'vertex'});if(path==='/api/ops/me')return response({principal:{subject:'admin-1',email:'admin@example.test',role:'admin'},permissions:['ai:approve','ai:draft']});if(path.startsWith('/api/ops/requests?'))return response({items:[record]});if(/^\/api\/ops\/(clients|tasks|documents)\?/.test(path))return response({items:[]});if(path.endsWith('/ai-approval')){writes.push(options);record={...record,version:2,aiUseApproval:{classification:'non_sensitive',validForVersion:2}};return response({item:record});}throw Error(path);});
 const d=dom.window.document;d.querySelector('[data-section="assistant"]').click();await flush();const approval=[...d.querySelectorAll('#ops-content button')].find(b=>b.textContent==='اعتماد تصنيف غير حساس للإصدار الحالي');assert.ok(approval);approval.click();await flush();assert.equal(writes.length,1);assert.ok([...d.querySelectorAll('#ops-content button')].some(b=>b.textContent.includes('إنشاء مسودة')));dom.window.close();
});
test('تاريخ المستند يعرض documentVersion وcreatedAt وaction الحقيقيين',async()=>{
 const record={id:'doc-1',title:'ملف اختبار',version:3,status:'approved',kind:'procedure',content:'اختبار'};
 const dom=await setup(async(path)=>{if(path==='/api/ops/config')return response(config);if(path==='/api/ops/me')return response({principal:{subject:'admin',email:'admin@example.test',role:'admin'},permissions:[]});if(path.startsWith('/api/ops/documents?'))return response({items:[record]});if(path.endsWith('/history'))return response({items:[{createdAt:'2026-10-08T00:00:00Z',documentVersion:3,action:'transition:documents',approval:{type:'internal_human_approval',legalSignature:false}}]});if(/^\/api\/ops\/(clients|tasks|requests)\?/.test(path))return response({items:[]});throw Error(path);});
 const d=dom.window.document;d.querySelector('[data-section="documents"]').click();await flush();[...d.querySelectorAll('#ops-content button')].find(b=>b.textContent==='سجل المراجعات').click();await flush();assert.match(d.querySelector('.ops-history-list').textContent,/3/);assert.match(d.querySelector('.ops-history-list').textContent,/2026-10-08/);assert.match(d.querySelector('.ops-history-list').textContent,/معتمد داخليًا/);dom.window.close();
});
test('نجاح حفظ ثم فشل تحديث القائمة لا يدعي أن القائمة حدثت',async()=>{
 let saved=false;const dom=await setup(async(path,options={})=>{if(path==='/api/ops/config')return response(config);if(path==='/api/ops/me')return response({principal:{subject:'admin',email:'admin@example.test',role:'admin'},permissions:['requests:write']});if(path==='/api/ops/requests'&&options.method==='POST'){saved=true;return response({item:{id:'saved',title:'طلب اختبار',version:1,status:'new'}});}if(path.startsWith('/api/ops/requests?'))return saved?response({error:'store_unavailable'},503):response({items:[]});if(/^\/api\/ops\/(clients|tasks|documents)\?/.test(path))return response({items:[]});throw Error(path);});
 const d=dom.window.document;d.querySelector('[data-section="requests"]').click();await flush();d.querySelector('#ops-toolbar-action button').click();d.querySelector('#ops-form').elements.namedItem('title').value='طلب اختبار';d.querySelector('#ops-form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));await flush();assert.equal(saved,true);assert.match(d.querySelector('#ops-live').textContent,/تم الحفظ، لكن تعذر تحديث القائمة/);assert.equal(d.querySelector('#ops-live').textContent.includes('وتحديث القائمة'),false);dom.window.close();
});
